### PR TITLE
xargs is async

### PR DESCRIPTION
**Pull request by sigmaSd**
kind of annoying it doesn't warn about mismatch between types

### CODE REVIEW

**Comment by sigmaSd** [comment]
not sure if there is a lint , or way to write things that improve things to get caught at compile time, since now it feels like the deceleration of types and the actual functions can go out of sync easily

**Comment by sigmaSd** [comment]
ah actually they are in sync, the root problem is that it seems in javascript Promise<void> is considered the same as void for types

**Comment by impactaky** [comment]
Thank you!
I notice it might be more convenient to return CommandBuilder[].
How do you think about this?

**Comment by sigmaSd** [comment]
yeah true, there is no reason to stop the chain call in xargs

**Comment by sigmaSd** [comment]
I wonder how can that be implemetned
```ts
  async xargs(command: (arg0: string) => CommandBuilder) {
    const processes: CommandBuilder[] = [];
    for await (const line of this.stream) {
        processes.push(command(line));
    }
    await Promise.all(processes);
  }
```
should we await all process expect the last one or something (does that even work) , or I'm missing something straightforward

**Comment by impactaky** [comment]
I see...
We'll just return Promise.all for now.

**Comment by impactaky** [comment]
The original LineStream.xargs was not returning a value, so could you please take a look at this one?

**Comment by sigmaSd** [comment]
questions:
- why PromiseLike instead of Promise (it currently gives a type error)
- instead of CommandResult[] I think we should return the last CommandResult, seems more intuitive to me

**Comment by impactaky** [comment]
Thank you for your review!

> why PromiseLike instead of Promise (it currently gives a type error)

I made a mistake looking at the return value of CommandBuilder. (And I missed the LSP warning...)

> instead of CommandResult[] I think we should return the last CommandResult, seems more intuitive to me

I think this xargs implementation executes the commands in parallel, so it is not clear which result is last. 
Given the behavior of xargs, this function should execute one command at a time...! (And add the -P option)

**Comment by impactaky** [comment]
I noticed that xargs should be spawned to generate the process. 
Once #5 is taken in, close this PR.

**Pull request closed without merging**
